test_git/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from testAPP.views import index, show_question, save_question, question_image, practise_is_correct, import_xlsx, question_random, edit_question, del_question

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),

    path('question/<int:pk>/info/', question_image, name='question_image'),
    path('question/', show_question, name='show_question'),
    path('save_question/', save_question, name='save_question'),
    path('edit_question/<int:pk>/edit/', edit_question, name='edit_question'),
    path('del_question/', del_question),
    path('import/', import_xlsx),
    path('random_question/', question_random, name='question_random'),

    path('practise_is_correct/', practise_is_correct),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)       # 能够在目录中正确的找到工作目录

testAPP/models.py
from django.db import models


# Create your models here.

class Question(models.Model):
    content = models.TextField(verbose_name="题目内容", primary_key=False, blank=False)
    label = models.TextField(verbose_name="题目分类", primary_key=False, blank=False, default='网络')
    DIFFICULTY_CHOICES = (
        ("E", '简单'),
        ("M", '中等'),
        ("H", '困难'),
    )
    difficulty = models.CharField(verbose_name="题目难度", max_length=1, choices=DIFFICULTY_CHOICES)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    QUESTION_TYPE_CHOICES = (
        ('S', '单项选择'),
        ('M', '多项选择'),
        ('F', '填空'),
    )
    question_type = models.CharField(max_length=1, choices=QUESTION_TYPE_CHOICES, verbose_name="题目类型")

    def __str__(self):
        return self.content

    # 钩子函数，将返回choices定义的数据
    def get_question_type_display(self):
        return dict(self.QUESTION_TYPE_CHOICES)[self.question_type]

    def get_difficulty_display(self):
        return dict(self.DIFFICULTY_CHOICES)[self.difficulty]


# 存储选项内容
class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 将关联题目id编号
    content = models.TextField()
    is_correct = models.BooleanField(default=False)  # 是否正确，默认是错误选项

    def __str__(self):
        return self.content

templates/question/edit_question.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <h2>题目{{ pk }}</h2>
    <span>题干</span><input type="text" name="content">
{% endblock %}

{% block js %}
    <script src="{% static 'js/question/edit_question.js' %}"></script>
{% endblock %}

templates/question/import_question.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>录入题目</title>
    <link href="{% static 'css/question/import_question.css' %}" rel="stylesheet" type="text/css">

</head>
<body>
    <h2>导入题目</h2>
    <h3>使用文件进行导入题目</h3>
    <form method="post" enctype="multipart/form-data" action='/import/'>
        {% csrf_token %}
        <div>
            <label for="id_image">选择xlsx文件进行导入：</label>
            <input type="file" name="xlsx" id="id_image" accept=".xlsx,">
        </div>
        <a href="{% static '题目导入-测试.xlsx' %}" download="题目导入-测试.xlsx" target="_parent">点击下载模板文件</a>
        <div>
            <input type="submit" value="上传">
        </div>
    </form>
    <hr>
    <h3>导入题目</h3>
    <h4 style="color: red">{{ error_message }}</h4>
    <form method="post" enctype="multipart/form-data" action='/save_question/'>
          {% csrf_token %}
          <div>
            <label for="id_content">问题内容：</label>
            <textarea name="content" id="id_content" placeholder="请输入题目"></textarea>
          </div>

          <div>
              <label for="id_question_type">问题类型：</label>
              <select id="id_question_type" name="question_type">
                  <option value="S">单项选择</option>
                  <option value="M">多项选择</option>
                  <option value="F">填空</option>
              </select>
          </div>
        <div>
            <label for="option1">选项1：</label>
              <input type="text" name="option1" id="option1" required><br>

              <label for="option2">选项2：</label>
              <input type="text" name="option2" id="option2" required><br>

              <label for="option3">选项3：</label>
              <input type="text" name="option3" id="option3" required><br>

              <label for="option3">选项4：</label>
              <input type="text" name="option4" id="option4" required><br>

            <div>
                <label for="correct_options">正确答案：</label>
                <select name="correct_options" id="correct_options">
                    <option value="1">选项1</option>
                    <option value="2">选项2</option>
                    <option value="3">选项3</option>
                    <option value="4">选项4</option>
                </select>
            </div>
        </div>
          <div>
            <label for="id_image">选择图片：</label>
            <input type="file" name="image" id="id_image" accept="image/*">

          </div><br>
        <div class="difficulty">
            <label for="id_difficulty">问题难度：</label>

            <input type="radio" id="easy" name="difficulty" value="E" checked="checked">
            <label for="easy">简单</label>

            <input type="radio" id="medium" name="difficulty" value="M">
            <label for="medium">中等</label>

            <input type="radio" id="hard" name="difficulty" value="H">
            <label for="hard">困难</label>
          </div>
            <div>
                <label for="type_question">题目分类：</label>
                    <select name="type_question" id="type_question">
                        <option value="网络">网络</option>
                        <option value="架构">架构</option>
                        <option value="计算">计算</option>
                        <option value="其他">其他</option>
                    </select>
            </div>
          <div>
            <input type="submit" value="上传">
          </div>

    </form>
    <hr>

    <h2>题目列表</h2>
  <table>
    <thead>
      <tr>
        <th>题号</th>
        <th>内容</th>
        <th>难度</th>
      </tr>
    </thead>
    <tbody>
      {% for question in msg %}
        <tr>
          <td>第{{ question.id }}题：</td>
          <td><a href="{% url 'question_image' pk=question.pk %}">{{ question.content }}</a></td>
          <td>{{ question.get_difficulty_display }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

</body>
</html>

templates/question/random_question.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2>随机答题</h2>
    <hr>
    <table id="question-table">
        <thead>
            <tr>
{#                <th>题号</th>#}
                <th>题目</th>
                <th>难度</th>
            </tr>
        </thead>
        <tbody>
        {% for question in question_list %}
            <tr>
{#                <td>{{ question.id }}</td>#}
                <td><a href="{% url 'question_image' pk=question.id %}">{{ question.content }}</a></td>
                <td>{{ question.get_difficulty_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block css %}

    <link href="{% static 'css/question/random_question.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block js %}
    <script src="{% static 'js/question/random_question.js' %}"></script>
{% endblock %}

templates/question/show_question.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2 class="content_type">{{ question_type }}</h2>
    <h4>题目：<label class="content">{{ content }}</label></h4>
    {% if image %}
        <img src="data:image/jpeg;base64,{{ image }}" /> <!--对图片进行编码设置-->
    {% endif %}
    {% for i, j in options %}
        <div class="difficulty">
            <input class="checkbox" type="checkbox" type="radio" name="difficulty">
            <label class="checkbox-label">{{ i }}.{{ j }}</label>
        </div>
    {% endfor %}

{% endblock %}
{% block css %}

    <link href="{% static 'css/question/show_question.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block js %}
    <script src="{% static 'js/question/show_question.js' %}"></script>
{% endblock %}

templates/question/show_question_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <h1>题目列表</h1><hr>
    <form>
        <input type="text" id="search" placeholder="> 输入你想搜索的题目...">
        <button type="submit" id="search-btn">搜索</button>
    </form>
    <table id="question-table">
        <thead>
            <tr>
                <th>题号</th>
                <th>题目</th>
                <th>难度</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        {% for question in question_list %}
            <tr>
                <td id="{{ question.id }}">{{ question.id }}</td>
                <td><a href="{% url 'question_image' pk=question.pk %}">{{ question.content }}</a></td>
                <td>{{ question.get_difficulty_display }}</td>
                <td><button onclick="window.location.href='{% url 'edit_question' pk=question.pk %}'">修改</button><button class="delButton" delId="{{ question.id }}">删除</button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div id="myModal" class="modal">
        <div class="modal-content">
            <p>确定要删除吗？</p>
            <button id="confirmBtn" style="background-color: red;">确认</button>
            <button id="cancelBtn">取消</button>
        </div>
    </div>
    <div id="alertBox" class="alert hidden"></div>
{% endblock %}

{% block css %}
    <link href="{% static 'css/question/show_question_list.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block js %}
    <script src="{% static 'js/question/show_question_list.js' %}"></script>
{% endblock %}